### ISSUE TITLE
deleteManyResources api doc

### ISSUE THREAD

**Issue by mereacre** [nqminds/nqm-api-tdx#19] opened 2019-06-21 13:51 UTC
Need to add an example explaining how deleteManyResources work.
As input it accepts an array of object of the type:
```javascript
[
{id: "datasetid1"},
{id: "datasetid2"}
]
```

Thanks to @IGlautier

**Comment by iendjinn** [comment] 2019-06-21 13:53
I believe this is a bug. The command validator here: https://github.com/nqminds/nqm-tdx/blob/master/packages/nqm-core-command-validators/lib/command-validators/resource-cmd-validator.js#L732

Maps an array of strings as if each element had a property "id". 

A call to deleteManyResources currently fails with:

https://github.com/nqminds/nqm-tdx/blob/master/packages/nqm-core-command-validators/lib/command-validators/resource-cmd-validator.js#L732

**Comment by iendjinn** [comment] 2019-06-21 13:57
The documentation is incorrect, this is not a bug.

**Comment by TobyEalden** [comment] 2019-06-24 05:29
Fixed in cd0662feb792e1dcaac20e9fa85e757e8391cb32

**Closed as completed by TobyEalden** 2019-06-24 05:29 UTC
